package control

import chisel3._
import chisel3.util._

/**
  * URAM-backed output memory (1 write port, 1 read port) with an internal read
  * pipeline, emitted as a BlackBox so we can attach the `(* ram_style = "ultra" *)`
  * attribute that forces Vivado to infer UltraRAM — something CIRCT cannot put on
  * a `SyncReadMem` (its `AttributeAnnotation` only targets modules/wires/regs).
  *
  * Why a BlackBox instead of post-processing the generated SV: the deep output
  * memory (batchSize * numColTilesMax * outSubBeats rows) maps to a long read
  * cascade. URAM has a hardware-pipelined cascade, but the pipeline registers must
  * live *inside* the memory module to pack into the cascade — external registers
  * (in Core) get SRL-optimized and never pipeline the cascade. Owning the module
  * lets us put `latency` registered stages right on the read path.
  *
  * Read semantics: `rdata` is the value at `raddr` delayed by `latency` cycles,
  * advanced only when `ren` is high (so the store FSM can stall on backpressure
  * without corrupting the pipeline). Write is synchronous on `wen`, delayed by
  * `writeLat` extra registered stages (see below).
  *
  * Why the write port is also pipelined (`writeLat`): the drain engine feeds a
  * combinational write address (`drainBatchCtr * numColTiles + …`, Core.scala)
  * straight into the URAM. As the output memory deepens with batchSize (B=6 →
  * 48000 rows), that address arithmetic + the route to the first URAM is the
  * 250 MHz critical path (post-route WNS −0.74 ns at B=6/B=8, congestion-free).
  * `writeLat` registered stages on waddr/wen/wdata — like `rpipe` for reads —
  * terminate the arithmetic at flops adjacent to the URAM so the deep cascade's
  * CAS_IN_ADDR starts from a register, not combinational logic routed across the
  * die. The drain writes during COMPUTE and the matching read happens in a later
  * STORE instruction, so the extra write latency is hidden (Core extends the
  * drain-completion gate by `writeLat` so a STORE issued off the IRQ still sees
  * the last write landed).
  *
  * The module name encodes the geometry + latencies so distinct instantiations
  * get distinct inline SV (BlackBoxInline keys on the file/module name).
  */
class OutMemUltra(depth: Int, width: Int, latency: Int, writeLat: Int = 1, cascadeHeight: Int = 4)
    extends BlackBox with HasBlackBoxInline {
  require(depth > 0 && width > 0 && latency >= 1 && writeLat >= 1 && cascadeHeight >= 1)
  private val aw = log2Ceil(depth)

  val io = IO(new Bundle {
    val clk   = Input(Clock())
    val waddr = Input(UInt(aw.W))
    val wen   = Input(Bool())
    val wdata = Input(UInt(width.W))
    val raddr = Input(UInt(aw.W))
    val ren   = Input(Bool())
    val rdata = Output(UInt(width.W))
  })

  override val desiredName = s"OutMemUltra_${depth}x${width}_l${latency}_w${writeLat}_c${cascadeHeight}"

  setInline(
    s"$desiredName.sv",
    s"""// Generated by control.OutMemUltra — URAM output memory, read latency=$latency.
       |module $desiredName(
       |  input                clk,
       |  input  [${aw - 1}:0] waddr,
       |  input                wen,
       |  input  [${width - 1}:0] wdata,
       |  input  [${aw - 1}:0] raddr,
       |  input                ren,
       |  output [${width - 1}:0] rdata
       |);
       |  // cascade_height bounds the URAM chain length so the read-data AND
       |  // write-address cascades stay short enough for 250 MHz (a single deep
       |  // chain over all ${depth / 4096 + 1}~ URAMs is a 7-deep combinational cascade that fails).
       |  (* ram_style = "ultra", cascade_height = $cascadeHeight *) reg [${width - 1}:0] mem [0:${depth - 1}];
       |
       |  // `writeLat` registered write stages. shreg_extract="no" keeps them as
       |  // flops (not SRLs) so the placer puts them adjacent to the URAM write
       |  // port — the external address arithmetic (drainBatchCtr*numColTiles+…)
       |  // ends at a flop here, so the URAM cascade's CAS_IN_ADDR no longer starts
       |  // from combinational logic routed across the die (the B>=6 critical path).
       |  (* shreg_extract = "no" *) reg [${aw - 1}:0]    waddr_q [0:${writeLat - 1}];
       |  (* shreg_extract = "no" *) reg                  wen_q   [0:${writeLat - 1}];
       |  (* shreg_extract = "no" *) reg [${width - 1}:0] wdata_q [0:${writeLat - 1}];
       |  integer j;
       |  always @(posedge clk) begin
       |    waddr_q[0] <= waddr; wen_q[0] <= wen; wdata_q[0] <= wdata;
       |    for (j = 1; j < $writeLat; j = j + 1) begin
       |      waddr_q[j] <= waddr_q[j - 1]; wen_q[j] <= wen_q[j - 1]; wdata_q[j] <= wdata_q[j - 1];
       |    end
       |  end
       |  always @(posedge clk) if (wen_q[${writeLat - 1}]) mem[waddr_q[${writeLat - 1}]] <= wdata_q[${writeLat - 1}];
       |
       |  // `latency` registered read stages. shreg_extract="no" keeps them as
       |  // flops (not SRLs) so the tool packs them into the URAM cascade pipeline
       |  // registers — an SRL would sit after the whole cascade and pipeline
       |  // nothing. Gated by `ren` so the store FSM can stall without data loss.
       |  (* shreg_extract = "no" *) reg [${width - 1}:0] rpipe [0:${latency - 1}];
       |  integer i;
       |  always @(posedge clk) if (ren) begin
       |    rpipe[0] <= mem[raddr];
       |    for (i = 1; i < $latency; i = i + 1) rpipe[i] <= rpipe[i - 1];
       |  end
       |  assign rdata = rpipe[${latency - 1}];
       |endmodule
       |""".stripMargin
  )
}
